### ISSUE TITLE
[BUG] Asset warnings on load

### ISSUE THREAD

**Issue by dineshm72** [ironmonk88/monks-bloodsplats#26] opened 2023-09-10 14:54 UTC
**Describe the bug**
Using the latest MBS, on load you get a bunch of warnings about missing assets.

I'm not sure what the defaults are supposed to look like, but most of the types are not set, maybe as a result?

**To Reproduce**
1. Enable module
2. Load into game

You get a bunch of warnings like this:
earcut.js:128 [Assets] Asset id /modules/monks-bloodsplats/images/blood/29.webp was not found in the Cache
get @ earcut.js:128
earcut.js:128 [Assets] Asset id /modules/monks-bloodsplats/images/blood/99.webp was not found in the Cache
get @ earcut.js:128
earcut.js:128 [Assets] Asset id /modules/monks-bloodsplats/images/scorch/6.webp was not found in the Cache
get @ earcut.js:128
earcut.js:128 [Assets] Asset id /modules/monks-bloodsplats/images/blood/201.webp was not found in the Cache
get @ earcut.js:128
earcut.js:128 [Assets] Asset id /modules/monks-bloodsplats/images/scorch/3.webp was not found in the Cache

<img width="439" alt="image" src="https://github.com/ironmonk88/monks-bloodsplats/assets/2231877/730ab0ef-f334-4836-adf6-74318cd5b183">

This is what the default settings look like for me.  Not sure if it's intended to be more filled out.  I added bones to undead and it seemed to work fine.
<img width="1148" alt="image" src="https://github.com/ironmonk88/monks-bloodsplats/assets/2231877/2240b30f-b943-43b2-bb26-9867bd761ddc">

This is with just MBS, FTC, and a few libraries enabled.

**Expected behavior**
No warnings.  And possibly the defaults better set up?

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser [e.g. chrome, safari] Chrome
 - Foundry Version [e.g. v9] v11.308
 - System [e.g. D&D5e, Pathfinder 2e] 5e 2.3.1
 - Module version 11.03
 - Are there any errors in the console [e.g. press F12 and look for red text] as above
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. as above

**Additional context**

**Comment by ironmonk88** [comment] 2023-09-10 16:18
Not intended to be more filled out.  I've left it to users personal preference.
And those are just warnings that the particular image hasn't been loaded before, and letting you know it's about to be loaded.

**Comment by ironmonk88** [comment] 2023-09-30 05:45
Closing this as it's either working as intended or the message has been removed.

**Closed by ironmonk88** 2023-09-30 05:45 UTC
